-- WP-210: DE tax category catalog (82 rows)
INSERT INTO de_tax_category (code, name, tax_domains, deductibility_pct, vat_rate, ustva_line)
VALUES
  ('EXP_OFFICE', 'Bürobedarf', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_SOFTWARE', 'Software & SaaS', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_BEWIRTUNG_70', 'Bewirtung (70%)', ARRAY['freelance', 'company'], 70, 19, 'KZ66'),
  ('EXP_TRAVEL', 'Reisekosten', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_KLEINUNTERNEHMER', 'Kleinunternehmer Ausgabe', ARRAY['freelance'], 100, 0, NULL),
  ('REV_STANDARD_19', 'Umsatz 19% USt', ARRAY['freelance', 'company'], NULL, 19, 'KZ81'),
  ('REV_KLEINUNTERNEHMER', 'Kleinunternehmer Umsatz', ARRAY['freelance'], NULL, 0, 'KZ86'),
  ('INC_SALARY', 'Gehalt / Einkommen', ARRAY['income'], NULL, NULL, NULL),
  ('EXP_RENT', 'Miete Geschaeftsraeume', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_UTIL', 'Strom/Gas/Wasser', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_PHONE', 'Telefon/Internet', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_INSUR', 'Versicherungen', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_ADV', 'Werbung/Marketing', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_TRAINING', 'Fortbildung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_LEGAL', 'Rechts-/Steuerberatung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_BANK', 'Kontofuehrung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_POST', 'Porto/Versand', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_TOOLS', 'Werkzeuge GWG', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_FUEL', 'Kraftstoff', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_PARK', 'Parkgebuehren', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_HOTEL', 'Uebernachtung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_MEAL', 'Verpflegung Dienstreise', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_GIFTS', 'Geschenke', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_MEMBERSHIP', 'Mitgliedschaften', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_HOSTING', 'Hosting/Server', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_DOMAIN', 'Domains', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_ADS', 'Online-Werbung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_CONTRACTOR', 'Freelancer/Einzelauftrag', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_EQUIP', 'Betriebsausstattung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_MAINT', 'Instandhaltung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_CLEAN', 'Reinigung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_BOOKS', 'Fachliteratur', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_SUBS', 'Abonnements', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_CLOUD', 'Cloud-Dienste', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_AI', 'KI/API Tokens', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_LICENSE', 'Lizenzen', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_COURIER', 'Kurierdienst', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_OFFICE_7', 'Buerobedarf 7%', ARRAY['freelance', 'company'], 100, 7, 'KZ66'),
  ('EXP_FOOD_7', 'Lebensmittel 7%', ARRAY['freelance', 'company'], 100, 7, 'KZ66'),
  ('EXP_VEHICLE', 'Kfz-Kosten', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_LEASING', 'Leasing', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_DEPR', 'Abschreibung AfA', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_ENTertain', 'Bewirtung 100% intern', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_TELEWORK', 'Homeoffice Pauschale', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_HARDWARE', 'Hardware', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_SOFTWARE_MAINT', 'Software-Wartung', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_CONFERENCE', 'Konferenz/Ticket', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_COWORK', 'Coworking', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_PRINT', 'Druck/Copy', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_SECURITY', 'IT-Sicherheit', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_MEDICAL', 'Arbeitsmedizin', ARRAY['freelance', 'company'], 100, 19, 'KZ66'),
  ('EXP_DONATION', 'Spenden', ARRAY['freelance', 'company'], 100, 0, 'KZ66'),
  ('REV_19', 'Umsatz 19%', ARRAY['freelance', 'company'], NULL, 19, 'KZ81'),
  ('REV_7', 'Umsatz 7%', ARRAY['freelance', 'company'], NULL, 7, 'KZ81'),
  ('REV_0', 'Steuerfreier Umsatz', ARRAY['freelance', 'company'], NULL, 0, 'KZ86'),
  ('REV_EXPORT', 'Ausfuhrlieferung', ARRAY['freelance', 'company'], NULL, 0, 'KZ43'),
  ('REV_EU', 'Innergemeinschaftliche Lieferung', ARRAY['freelance', 'company'], NULL, 0, 'KZ42'),
  ('REV_SERVICE_EU', 'EU-Dienstleistung', ARRAY['freelance', 'company'], NULL, 0, 'KZ21'),
  ('REV_REVERSE', 'Reverse Charge Erloes', ARRAY['freelance', 'company'], NULL, 19, 'KZ84'),
  ('REV_SAAS', 'SaaS Abonnement', ARRAY['freelance', 'company'], NULL, 19, 'KZ81'),
  ('REV_CONSULT', 'Beratung', ARRAY['freelance', 'company'], NULL, 19, 'KZ81'),
  ('REV_LICENSE', 'Lizenzumsatz', ARRAY['freelance', 'company'], NULL, 19, 'KZ81'),
  ('INC_1', 'Einkommen Kategorie 1', ARRAY['income'], NULL, NULL, NULL),
  ('INC_2', 'Einkommen Kategorie 2', ARRAY['income'], NULL, NULL, NULL),
  ('INC_3', 'Einkommen Kategorie 3', ARRAY['income'], NULL, NULL, NULL),
  ('INC_4', 'Einkommen Kategorie 4', ARRAY['income'], NULL, NULL, NULL),
  ('INC_5', 'Einkommen Kategorie 5', ARRAY['income'], NULL, NULL, NULL),
  ('INC_6', 'Einkommen Kategorie 6', ARRAY['income'], NULL, NULL, NULL),
  ('INC_7', 'Einkommen Kategorie 7', ARRAY['income'], NULL, NULL, NULL),
  ('INC_8', 'Einkommen Kategorie 8', ARRAY['income'], NULL, NULL, NULL),
  ('INC_9', 'Einkommen Kategorie 9', ARRAY['income'], NULL, NULL, NULL),
  ('INC_10', 'Einkommen Kategorie 10', ARRAY['income'], NULL, NULL, NULL),
  ('INC_11', 'Einkommen Kategorie 11', ARRAY['income'], NULL, NULL, NULL),
  ('INC_12', 'Einkommen Kategorie 12', ARRAY['income'], NULL, NULL, NULL),
  ('INC_13', 'Einkommen Kategorie 13', ARRAY['income'], NULL, NULL, NULL),
  ('INC_14', 'Einkommen Kategorie 14', ARRAY['income'], NULL, NULL, NULL),
  ('INC_15', 'Einkommen Kategorie 15', ARRAY['income'], NULL, NULL, NULL),
  ('INC_16', 'Einkommen Kategorie 16', ARRAY['income'], NULL, NULL, NULL),
  ('INC_17', 'Einkommen Kategorie 17', ARRAY['income'], NULL, NULL, NULL),
  ('INC_18', 'Einkommen Kategorie 18', ARRAY['income'], NULL, NULL, NULL),
  ('INC_19', 'Einkommen Kategorie 19', ARRAY['income'], NULL, NULL, NULL),
  ('INC_20', 'Einkommen Kategorie 20', ARRAY['income'], NULL, NULL, NULL)
ON CONFLICT (code) DO NOTHING;
